version: 2

models:
  - name: stg_users
    description: client information of all greenery clients
    columns:
    - name: user_id
      tests:
        - not_null
  - name: stg_addresses
    description: client addresses of all greenery clients
    columns:
    - name: address_id
      tests:
        - not_null
  - name: stg_events
    description: Event tracking of client sessions
    columns:
    - name: event_id
      tests:
        - not_null
  - name: stg_orders
    description: Order information for all client orders
    columns:
    - name: order_id
      tests:
        - not_null
  - name: stg_orderitems
    description: connecting products and orders
    columns:
    - name: order_id
      tests:
        - not_null
  - name: stg_promos
    description: All promo information
    columns:
    - name: promo_id
      tests:
        - not_null
  - name: stg_products
    description: All products for sale
    columns:
    - name: product_id
      tests:
        - not_null