version: 2

models:
  - name: fct_session_events
    description: All the session related information with session as grain
  - name: fct_product_events
    description: Combining products with orders and sessions